pipeline {

    agent none 
    stages {
        stage('maven version check') {
            steps {
                
                bat 'mvn -v'
            }
        }
        stage('execute maven build') {
            steps {
               
               bat 'mvn clean verify'
            }
        }
        
         stage('generate cucumber report') {
            steps {  
               cucumber fileIncludePattern: 'cucumber.json', jsonReportDirectory: 'C:\\Users\\VIJAY\\git\\Pos-Complete\\Windows\\target\\cucumber-reports', reportTitle: 'Windows cucumber report', sortingMethod: 'ALPHABETICAL'
            }
        }
    
      stage('send email') {
            steps {
               
      mail bcc: '', body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
    Check console output at $BUILD_URL to view the results.''', cc: '', from: '', replyTo: '', subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'vijayautomationtest@gmail.com'

            }
        }
    
    }
}